substitutions:
  name: esp32-aquarium-water
  friendly_name: "Aquarium"
  include_path: "./"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_encryption: !secret api_encryption
  ota_password: !secret ota_password

<<: !include .aquarium_config.yaml
